run:
  timeout: 10m
  skip-files: []

linters-settings:
  custom:
    example:
      # Path to the `.so` file of the plugin
      path: .plugins/example.so
      # Only used for documentation purposes.
      description: The description of the linter. Shows up when running `golangci-lint linters`.
      # Only used for documentation purposes.
      original-url: github.com/golangci/example-linter

linters:
  disable-all: true
  enable:
    - example
    - typecheck

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0

